### PR TITLE
add enable editor tab in global mode

### PR DESCRIPTION
**Pull request by yaming116**
Add an optional option to edit profile information using the web editor in global mode

### CODE REVIEW

**Comment by Apollon77** [comment]
Do you see an way to improve on "guidance" for the user that the "former manually edited file" is now handled by the adapter? Becaue in this concept all manual changes would be overwritten on adater start. Also all existing content once starting with this is also overwritten ... So maybe implement reading the existing file initially?!

**Comment by Apollon77** [comment]
Thank you, I will have a look into it in the next days

**Comment by yaming116** [comment]
I looked at the iobroker api, did not find where to preload the local configuration file, currently only users manually enable this configuration will generate a problem of overwriting local files

**Comment by Apollon77** [comment]
We could add a new message to the adapter code to allow to read the local config and return via socketio to the admin page (this communication works well) so once activating in admin we could load that config into the editor or ask the user what should happen

**Comment by yaming116** [comment]
I don't think there is a file in the current location. It is just a copy file configured on the interface, so there is no need to do any checks.

**Comment by Apollon77** [comment]
Sorry for the late response.

I'm about to provide a 1.1.0 with a new mode of the adapter, called "local mode". This installs a local homebridge that handles everything via the adapter including config.

Is then a globla mode json editor still needed? What do you think?

**Comment by yaming116** [comment]
good news, I will test it.

**Comment by Apollon77** [comment]
So this means you think we do not need that anymore then? :-)

**Comment by yaming116** [comment]
I simply tested it and there is no problem at the moment. I will use it in depth for a while to see the results. At present, some friends in China really like the ham model, which makes them very practical for homebridge.

**Pull request closed without merging**
